"""Mission plan format, validation, and survey-grid generation.

The plan format is YAML because that is what everyone already edits by hand and
what ROS 2 parameters use. A plan is a header plus an ordered list of items::

    name: field_survey
    origin: {latitude: 47.397742, longitude: 8.545594, altitude: 488.0}
    default_speed: 5.0
    items:
      - {type: takeoff, altitude: 30.0}
      - {type: waypoint, latitude: 47.3980, longitude: 8.5460, altitude: 30.0,
         speed: 6.0, acceptance_radius: 2.0, hold_time: 3.0}
      - {type: survey, altitude: 40.0, spacing: 20.0, heading: 90.0,
         polygon: [[lat, lon], ...]}
      - {type: orbit, latitude: ..., longitude: ..., altitude: 35.0,
         radius: 25.0, turns: 2.0}
      - {type: rtl}
      - {type: land}

Design notes
------------
* Validation is **eager and specific**. Every error names the item index, its
  declared type, and the offending field, because a mission that half-loads and
  then fails at item 14 mid-flight is much worse than one that refuses to load
  on the bench.
* :meth:`Mission.expand` flattens composite items (``survey``, ``orbit``) into
  plain waypoints. Everything downstream -- the state machine, the executor
  node -- only ever deals with the flat list, so there is exactly one place
  where geometry happens.
* Survey grids are generated by real polygon scanline fill in the local ENU
  plane, not by walking a bounding box. Lines run along a configurable heading,
  are spaced by a configurable swath, and alternate direction (boustrophedon)
  so the vehicle never deadheads back across the field.

Pure Python plus PyYAML. No ROS.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Sequence, Tuple

from .geodesy import LocalOrigin, wrap_2pi
from .geofence import point_in_polygon, polygon_centroid

try:  # pragma: no cover - trivial import guard
    import yaml
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore[assignment]

__all__ = [
    "MissionError",
    "MissionValidationError",
    "ItemType",
    "Waypoint",
    "MissionItem",
    "TakeoffItem",
    "WaypointItem",
    "SurveyItem",
    "OrbitItem",
    "RTLItem",
    "LandItem",
    "Mission",
    "generate_lawnmower",
    "load_mission_file",
    "load_mission_yaml",
    "polygon_contains_geodetic",
    "polygon_centroid_geodetic",
]


class MissionError(Exception):
    """Base class for mission problems."""


class MissionValidationError(MissionError, ValueError):
    """A mission document is structurally or semantically invalid.

    The message always identifies *where* the problem is (``items[3] (survey)``)
    and *what* is wrong, so it can be surfaced straight to a ground station.
    """


class ItemType(str, Enum):
    """Supported mission item types."""

    TAKEOFF = "takeoff"
    WAYPOINT = "waypoint"
    SURVEY = "survey"
    ORBIT = "orbit"
    RTL = "rtl"
    LAND = "land"


# --- flattened output --------------------------------------------------------
@dataclass(frozen=True)
class Waypoint:
    """One concrete point the vehicle flies to.

    Altitudes are metres **above the mission origin** (local ENU Up), never
    AMSL. Speed is ground speed in m/s.
    """

    latitude: float
    longitude: float
    altitude: float
    speed: float
    acceptance_radius: float = 2.0
    hold_time: float = 0.0
    yaw_deg: Optional[float] = None
    label: str = ""

    def as_dict(self) -> Dict[str, Any]:
        """Plain-dict form, handy for logging or republishing."""
        return {
            "latitude": self.latitude,
            "longitude": self.longitude,
            "altitude": self.altitude,
            "speed": self.speed,
            "acceptance_radius": self.acceptance_radius,
            "hold_time": self.hold_time,
            "yaw_deg": self.yaw_deg,
            "label": self.label,
        }


# --- item types --------------------------------------------------------------
@dataclass(frozen=True)
class MissionItem:
    """Base mission item. Subclasses implement :meth:`expand`."""

    index: int = -1

    @property
    def type(self) -> ItemType:  # pragma: no cover - overridden
        raise NotImplementedError

    def expand(self, mission: "Mission") -> List[Waypoint]:  # pragma: no cover
        """Flatten this item into concrete waypoints."""
        raise NotImplementedError


@dataclass(frozen=True)
class TakeoffItem(MissionItem):
    """Climb vertically to ``altitude`` above the origin before proceeding."""

    altitude: float = 10.0

    @property
    def type(self) -> ItemType:
        return ItemType.TAKEOFF

    def expand(self, mission: "Mission") -> List[Waypoint]:
        origin = mission.origin
        return [
            Waypoint(
                latitude=origin.latitude_deg,
                longitude=origin.longitude_deg,
                altitude=self.altitude,
                speed=mission.default_speed,
                acceptance_radius=mission.default_acceptance_radius,
                label="takeoff",
            )
        ]


@dataclass(frozen=True)
class WaypointItem(MissionItem):
    """A single navigation waypoint."""

    latitude: float = 0.0
    longitude: float = 0.0
    altitude: float = 10.0
    speed: Optional[float] = None
    acceptance_radius: Optional[float] = None
    hold_time: float = 0.0
    yaw_deg: Optional[float] = None

    @property
    def type(self) -> ItemType:
        return ItemType.WAYPOINT

    def expand(self, mission: "Mission") -> List[Waypoint]:
        return [
            Waypoint(
                latitude=self.latitude,
                longitude=self.longitude,
                altitude=self.altitude,
                speed=self.speed if self.speed is not None else mission.default_speed,
                acceptance_radius=(
                    self.acceptance_radius
                    if self.acceptance_radius is not None
                    else mission.default_acceptance_radius
                ),
                hold_time=self.hold_time,
                yaw_deg=self.yaw_deg,
                label=f"wp{self.index}",
            )
        ]


@dataclass(frozen=True)
class SurveyItem(MissionItem):
    """A lawnmower/boustrophedon survey over a polygon."""

    polygon: Tuple[Tuple[float, float], ...] = ()
    altitude: float = 30.0
    spacing: float = 20.0
    heading: float = 0.0
    speed: Optional[float] = None
    acceptance_radius: Optional[float] = None
    line_extension: float = 0.0

    @property
    def type(self) -> ItemType:
        return ItemType.SURVEY

    def expand(self, mission: "Mission") -> List[Waypoint]:
        return generate_lawnmower(
            polygon=self.polygon,
            origin=mission.origin,
            altitude=self.altitude,
            spacing=self.spacing,
            heading_deg=self.heading,
            speed=self.speed if self.speed is not None else mission.default_speed,
            acceptance_radius=(
                self.acceptance_radius
                if self.acceptance_radius is not None
                else mission.default_acceptance_radius
            ),
            line_extension=self.line_extension,
            label_prefix=f"survey{self.index}",
        )


@dataclass(frozen=True)
class OrbitItem(MissionItem):
    """Circle a point at a fixed radius, discretised into waypoints."""

    latitude: float = 0.0
    longitude: float = 0.0
    altitude: float = 20.0
    radius: float = 20.0
    turns: float = 1.0
    clockwise: bool = True
    points_per_turn: int = 12
    speed: Optional[float] = None

    @property
    def type(self) -> ItemType:
        return ItemType.ORBIT

    def expand(self, mission: "Mission") -> List[Waypoint]:
        origin = mission.origin
        cx, cy, _ = origin.geodetic_to_enu(self.latitude, self.longitude, origin.altitude_m)
        n = max(3, int(round(self.points_per_turn * self.turns)))
        speed = self.speed if self.speed is not None else mission.default_speed
        sign = -1.0 if self.clockwise else 1.0
        out: List[Waypoint] = []
        for k in range(n + 1):
            frac = k / float(self.points_per_turn)
            ang = sign * 2.0 * math.pi * frac
            e = cx + self.radius * math.cos(ang)
            nn = cy + self.radius * math.sin(ang)
            lat, lon, _ = origin.enu_to_geodetic(e, nn, self.altitude)
            # Point the nose at the orbit centre; that is what a camera task wants.
            yaw = math.degrees(wrap_2pi(math.atan2(cy - nn, cx - e)))
            out.append(
                Waypoint(
                    latitude=lat,
                    longitude=lon,
                    altitude=self.altitude,
                    speed=speed,
                    acceptance_radius=mission.default_acceptance_radius,
                    yaw_deg=yaw,
                    label=f"orbit{self.index}_{k}",
                )
            )
        return out


@dataclass(frozen=True)
class RTLItem(MissionItem):
    """Return to launch. Expands to zero waypoints; the executor handles the mode."""

    @property
    def type(self) -> ItemType:
        return ItemType.RTL

    def expand(self, mission: "Mission") -> List[Waypoint]:
        return []


@dataclass(frozen=True)
class LandItem(MissionItem):
    """Land at the current position, or at an explicit point if given."""

    latitude: Optional[float] = None
    longitude: Optional[float] = None

    @property
    def type(self) -> ItemType:
        return ItemType.LAND

    def expand(self, mission: "Mission") -> List[Waypoint]:
        if self.latitude is None or self.longitude is None:
            return []
        return [
            Waypoint(
                latitude=self.latitude,
                longitude=self.longitude,
                altitude=0.0,
                speed=mission.default_speed,
                acceptance_radius=mission.default_acceptance_radius,
                label="land",
            )
        ]


# --- survey generation -------------------------------------------------------
def generate_lawnmower(
    polygon: Sequence[Tuple[float, float]],
    origin: LocalOrigin,
    altitude: float,
    spacing: float,
    heading_deg: float = 0.0,
    speed: float = 5.0,
    acceptance_radius: float = 2.0,
    line_extension: float = 0.0,
    label_prefix: str = "survey",
) -> List[Waypoint]:
    """Fill a geodetic polygon with a boustrophedon (lawnmower) path.

    Algorithm: project the polygon into local ENU metres, rotate it so the
    requested heading lies along +x, run a scanline fill at ``spacing`` metres,
    pair up the crossings into inside-segments, reverse every other line so the
    path is continuous, then rotate and unproject back to WGS84.

    Args:
        polygon: Boundary as ``[(lat, lon), ...]``, at least 3 vertices,
            implicitly closed.
        origin: Local tangent-plane origin used for the projection.
        altitude: Survey altitude, metres above the origin.
        spacing: Line spacing (sensor swath) in metres. Must be positive.
        heading_deg: Direction of the survey lines, degrees clockwise from
            north. 0 gives north-south lines, 90 gives east-west.
        speed: Ground speed assigned to every generated waypoint, m/s.
        acceptance_radius: Waypoint acceptance radius, metres.
        line_extension: Extend each line by this many metres at both ends so
            the vehicle is settled and on-heading before the sensor region
            starts. Costs flight time; buys usable imagery at the edges.
        label_prefix: Prefix for generated waypoint labels.

    Returns:
        Waypoints in flight order. Empty if the polygon has no interior at the
        requested spacing.

    Raises:
        MissionValidationError: If the polygon or spacing is unusable.

    The first line is offset half a spacing from the polygon's minimum extent,
    so each line sits in the middle of its own swath. That is what makes the
    union of swaths cover the polygon when swath width equals ``spacing``.
    """
    if len(polygon) < 3:
        raise MissionValidationError(
            f"survey polygon needs at least 3 vertices, got {len(polygon)}"
        )
    if spacing <= 0.0:
        raise MissionValidationError(f"survey spacing must be > 0, got {spacing}")
    if line_extension < 0.0:
        raise MissionValidationError(
            f"survey line_extension must be >= 0, got {line_extension}"
        )

    # 1. Project to local ENU metres.
    local = [
        origin.geodetic_to_enu(lat, lon, origin.altitude_m)[:2] for lat, lon in polygon
    ]

    # 2. Rotate so survey lines run along +x.
    #    heading is clockwise-from-north (compass); ENU angle CCW-from-east is
    #    (90 - heading). Rotating the polygon by -that angle puts lines on +x.
    theta = math.radians(90.0 - heading_deg)
    cos_t, sin_t = math.cos(-theta), math.sin(-theta)
    rot = [(x * cos_t - y * sin_t, x * sin_t + y * cos_t) for x, y in local]

    ys = [p[1] for p in rot]
    y_min, y_max = min(ys), max(ys)
    span = y_max - y_min
    if span <= 1e-6:
        raise MissionValidationError(
            "survey polygon is degenerate (zero extent across the survey heading)"
        )

    # 3. Scanline fill, first line half a swath in from the edge.
    n_lines = max(1, int(math.ceil(span / spacing)))
    # Centre the line set inside the polygon extent so both edges get equal margin.
    used = (n_lines - 1) * spacing
    y0 = y_min + (span - used) * 0.5
    if n_lines == 1:
        y0 = y_min + span * 0.5

    waypoints: List[Waypoint] = []
    cos_b, sin_b = math.cos(theta), math.sin(theta)
    line_index = 0
    for k in range(n_lines):
        y = y0 + k * spacing
        crossings = _scanline_crossings(rot, y)
        if len(crossings) < 2:
            continue
        segments = [
            (crossings[i], crossings[i + 1]) for i in range(0, len(crossings) - 1, 2)
        ]
        # Boustrophedon: reverse odd lines and the segment order within them.
        if line_index % 2 == 1:
            segments = [(b, a) for a, b in reversed(segments)]
        for x_start, x_end in segments:
            direction = 1.0 if x_end >= x_start else -1.0
            xs = x_start - direction * line_extension
            xe = x_end + direction * line_extension
            for x in (xs, xe):
                # rotate back into ENU, then unproject
                e = x * cos_b - y * sin_b
                n_ = x * sin_b + y * cos_b
                lat, lon, _ = origin.enu_to_geodetic(e, n_, altitude)
                waypoints.append(
                    Waypoint(
                        latitude=lat,
                        longitude=lon,
                        altitude=altitude,
                        speed=speed,
                        acceptance_radius=acceptance_radius,
                        label=f"{label_prefix}_l{line_index}",
                    )
                )
        line_index += 1
    return waypoints


def _scanline_crossings(
    vertices: Sequence[Tuple[float, float]], y: float
) -> List[float]:
    """X coordinates where the horizontal line ``y`` crosses the polygon, sorted.

    Uses the half-open rule ``min(y1, y2) <= y < max(y1, y2)`` so a vertex is
    counted exactly once and the crossing count stays even for a simple polygon.
    """
    out: List[float] = []
    n = len(vertices)
    for i in range(n):
        x1, y1 = vertices[i]
        x2, y2 = vertices[(i + 1) % n]
        if y1 == y2:
            continue
        lo, hi = (y1, y2) if y1 < y2 else (y2, y1)
        if lo <= y < hi:
            out.append(x1 + (y - y1) * (x2 - x1) / (y2 - y1))
    out.sort()
    return out


# --- the mission itself ------------------------------------------------------
@dataclass
class Mission:
    """A validated mission plan."""

    name: str
    origin: LocalOrigin
    items: List[MissionItem] = field(default_factory=list)
    default_speed: float = 5.0
    default_acceptance_radius: float = 2.0
    rtl_altitude: float = 30.0
    description: str = ""

    # -- expansion ----------------------------------------------------------
    def waypoint_to_enu(self, waypoint: Waypoint) -> Tuple[float, float, float]:
        """Local ENU metres for a waypoint, relative to :attr:`origin`.

        Waypoint altitude is already "metres above the origin", so it is
        returned as the Up component unchanged. The lat/lon are projected at the
        origin's own height, which keeps the horizontal projection exact and
        stops the origin's ellipsoidal height from leaking into Up.

        Getting this wrong is subtle and expensive: pass a 40 m relative
        altitude straight into :meth:`LocalOrigin.geodetic_to_enu` and you get
        ``40 - 488 = -448`` m Up, which as an offboard setpoint is a command to
        fly into the ground.
        """
        east, north, _ = self.origin.geodetic_to_enu(
            waypoint.latitude, waypoint.longitude, self.origin.altitude_m
        )
        return (east, north, waypoint.altitude)

    def expand(self) -> List[Waypoint]:
        """Flatten every item into a single ordered waypoint list."""
        out: List[Waypoint] = []
        for item in self.items:
            out.extend(item.expand(self))
        return out

    @property
    def item_types(self) -> List[ItemType]:
        """Item types in order -- convenient for asserting mission shape."""
        return [item.type for item in self.items]

    def total_ground_distance(self) -> float:
        """Sum of horizontal leg lengths across the expanded waypoints, metres."""
        pts = self.expand()
        total = 0.0
        for a, b in zip(pts, pts[1:]):
            ea, na, _ = self.waypoint_to_enu(a)
            eb, nb, _ = self.waypoint_to_enu(b)
            total += math.hypot(eb - ea, nb - na)
        return total

    def estimated_duration_s(self) -> float:
        """Rough flight time: legs at their commanded speed, plus hold times.

        This ignores acceleration, wind, and turn-around losses, so treat it as
        a lower bound. It is here so a planner can reject a mission that is
        obviously beyond endurance, not to promise a number.
        """
        pts = self.expand()
        total = sum(p.hold_time for p in pts)
        for a, b in zip(pts, pts[1:]):
            ea, na, ua = self.waypoint_to_enu(a)
            eb, nb, ub = self.waypoint_to_enu(b)
            dist = math.sqrt((eb - ea) ** 2 + (nb - na) ** 2 + (ub - ua) ** 2)
            speed = max(0.1, b.speed)
            total += dist / speed
        return total

    # -- parsing ------------------------------------------------------------
    @classmethod
    def from_dict(cls, data: Any) -> "Mission":
        """Validate and build a mission from a plain dict.

        Raises:
            MissionValidationError: On any structural or semantic problem, with
                a message that names the failing item and field.
        """
        if not isinstance(data, dict):
            raise MissionValidationError(
                f"mission root must be a mapping, got {type(data).__name__}"
            )
        name = data.get("name")
        if not isinstance(name, str) or not name.strip():
            raise MissionValidationError("mission: 'name' must be a non-empty string")

        origin_raw = data.get("origin")
        if not isinstance(origin_raw, dict):
            raise MissionValidationError(
                "mission: 'origin' must be a mapping with latitude/longitude"
            )
        for key in ("latitude", "longitude"):
            if key not in origin_raw:
                raise MissionValidationError(f"mission.origin: missing key '{key}'")
        try:
            origin = LocalOrigin(
                _as_float(origin_raw["latitude"], "mission.origin.latitude"),
                _as_float(origin_raw["longitude"], "mission.origin.longitude"),
                _as_float(origin_raw.get("altitude", 0.0), "mission.origin.altitude"),
            )
        except ValueError as exc:
            raise MissionValidationError(f"mission.origin: {exc}") from None

        default_speed = _positive(
            data.get("default_speed", 5.0), "mission.default_speed"
        )
        default_radius = _positive(
            data.get("default_acceptance_radius", 2.0),
            "mission.default_acceptance_radius",
        )
        rtl_alt = _positive(data.get("rtl_altitude", 30.0), "mission.rtl_altitude")

        raw_items = data.get("items")
        if not isinstance(raw_items, list) or not raw_items:
            raise MissionValidationError(
                "mission: 'items' must be a non-empty list of mission items"
            )

        items = [_parse_item(raw, i) for i, raw in enumerate(raw_items)]
        mission = cls(
            name=name,
            origin=origin,
            items=items,
            default_speed=default_speed,
            default_acceptance_radius=default_radius,
            rtl_altitude=rtl_alt,
            description=str(data.get("description", "")),
        )
        mission.validate()
        return mission

    def validate(self) -> None:
        """Re-run whole-mission checks that need more than one item to see.

        Raises:
            MissionValidationError: If the item sequence does not make sense.
        """
        types = self.item_types
        if not types:
            raise MissionValidationError("mission: no items")
        if types[0] is not ItemType.TAKEOFF:
            raise MissionValidationError(
                f"mission.items[0]: first item must be 'takeoff', got "
                f"'{types[0].value}'. A mission that starts with a waypoint will "
                f"fly the vehicle at ground level to the first leg."
            )
        if types[-1] not in (ItemType.LAND, ItemType.RTL):
            raise MissionValidationError(
                f"mission.items[{len(types) - 1}]: last item must be 'land' or "
                f"'rtl', got '{types[-1].value}'"
            )
        for i, t in enumerate(types[:-1]):
            if t in (ItemType.LAND, ItemType.RTL):
                raise MissionValidationError(
                    f"mission.items[{i}] ({t.value}): terminal item appears before "
                    f"the end of the mission; nothing after it will execute"
                )
        takeoffs = [i for i, t in enumerate(types) if t is ItemType.TAKEOFF]
        if len(takeoffs) > 1:
            raise MissionValidationError(
                f"mission: multiple 'takeoff' items at indices {takeoffs}; "
                f"only the first item may be a takeoff"
            )

    def to_dict(self) -> Dict[str, Any]:
        """Serialise the header and the expanded waypoints (not the raw items)."""
        return {
            "name": self.name,
            "description": self.description,
            "origin": {
                "latitude": self.origin.latitude_deg,
                "longitude": self.origin.longitude_deg,
                "altitude": self.origin.altitude_m,
            },
            "default_speed": self.default_speed,
            "default_acceptance_radius": self.default_acceptance_radius,
            "rtl_altitude": self.rtl_altitude,
            "waypoints": [wp.as_dict() for wp in self.expand()],
        }


# --- item parsing ------------------------------------------------------------
def _parse_item(raw: Any, index: int) -> MissionItem:
    """Build one :class:`MissionItem`, raising a located error on any problem."""
    where = f"mission.items[{index}]"
    if not isinstance(raw, dict):
        raise MissionValidationError(
            f"{where}: must be a mapping, got {type(raw).__name__}"
        )
    type_raw = raw.get("type")
    if type_raw is None:
        raise MissionValidationError(f"{where}: missing required key 'type'")
    try:
        item_type = ItemType(str(type_raw).lower())
    except ValueError:
        raise MissionValidationError(
            f"{where}: unknown type '{type_raw}'; expected one of "
            f"{[t.value for t in ItemType]}"
        ) from None
    where = f"{where} ({item_type.value})"

    if item_type is ItemType.TAKEOFF:
        alt = _positive(_require(raw, "altitude", where), f"{where}.altitude")
        return TakeoffItem(index=index, altitude=alt)

    if item_type is ItemType.WAYPOINT:
        lat = _latitude(_require(raw, "latitude", where), f"{where}.latitude")
        lon = _longitude(_require(raw, "longitude", where), f"{where}.longitude")
        alt = _as_float(_require(raw, "altitude", where), f"{where}.altitude")
        speed = _opt_positive(raw.get("speed"), f"{where}.speed")
        radius = _opt_positive(
            raw.get("acceptance_radius"), f"{where}.acceptance_radius"
        )
        hold = _non_negative(raw.get("hold_time", 0.0), f"{where}.hold_time")
        yaw = raw.get("yaw_deg")
        return WaypointItem(
            index=index,
            latitude=lat,
            longitude=lon,
            altitude=alt,
            speed=speed,
            acceptance_radius=radius,
            hold_time=hold,
            yaw_deg=None if yaw is None else _as_float(yaw, f"{where}.yaw_deg"),
        )

    if item_type is ItemType.SURVEY:
        poly_raw = _require(raw, "polygon", where)
        if not isinstance(poly_raw, list) or len(poly_raw) < 3:
            raise MissionValidationError(
                f"{where}.polygon: must be a list of at least 3 [lat, lon] pairs, "
                f"got {len(poly_raw) if isinstance(poly_raw, list) else type(poly_raw).__name__}"
            )
        poly: List[Tuple[float, float]] = []
        for j, v in enumerate(poly_raw):
            if not isinstance(v, (list, tuple)) or len(v) != 2:
                raise MissionValidationError(
                    f"{where}.polygon[{j}]: must be a [lat, lon] pair"
                )
            poly.append(
                (
                    _latitude(v[0], f"{where}.polygon[{j}][0]"),
                    _longitude(v[1], f"{where}.polygon[{j}][1]"),
                )
            )
        alt = _positive(_require(raw, "altitude", where), f"{where}.altitude")
        spacing = _positive(_require(raw, "spacing", where), f"{where}.spacing")
        heading = _as_float(raw.get("heading", 0.0), f"{where}.heading")
        return SurveyItem(
            index=index,
            polygon=tuple(poly),
            altitude=alt,
            spacing=spacing,
            heading=heading,
            speed=_opt_positive(raw.get("speed"), f"{where}.speed"),
            acceptance_radius=_opt_positive(
                raw.get("acceptance_radius"), f"{where}.acceptance_radius"
            ),
            line_extension=_non_negative(
                raw.get("line_extension", 0.0), f"{where}.line_extension"
            ),
        )

    if item_type is ItemType.ORBIT:
        lat = _latitude(_require(raw, "latitude", where), f"{where}.latitude")
        lon = _longitude(_require(raw, "longitude", where), f"{where}.longitude")
        alt = _positive(_require(raw, "altitude", where), f"{where}.altitude")
        radius = _positive(_require(raw, "radius", where), f"{where}.radius")
        turns = _positive(raw.get("turns", 1.0), f"{where}.turns")
        ppt = int(_positive(raw.get("points_per_turn", 12), f"{where}.points_per_turn"))
        if ppt < 3:
            raise MissionValidationError(
                f"{where}.points_per_turn: need at least 3 to approximate a circle, got {ppt}"
            )
        return OrbitItem(
            index=index,
            latitude=lat,
            longitude=lon,
            altitude=alt,
            radius=radius,
            turns=turns,
            clockwise=bool(raw.get("clockwise", True)),
            points_per_turn=ppt,
            speed=_opt_positive(raw.get("speed"), f"{where}.speed"),
        )

    if item_type is ItemType.RTL:
        return RTLItem(index=index)

    # LAND
    lat_raw = raw.get("latitude")
    lon_raw = raw.get("longitude")
    if (lat_raw is None) != (lon_raw is None):
        raise MissionValidationError(
            f"{where}: give both 'latitude' and 'longitude' for a positioned land, "
            f"or neither to land in place"
        )
    return LandItem(
        index=index,
        latitude=None if lat_raw is None else _latitude(lat_raw, f"{where}.latitude"),
        longitude=None if lon_raw is None else _longitude(lon_raw, f"{where}.longitude"),
    )


# --- validation helpers ------------------------------------------------------
def _require(raw: Dict[str, Any], key: str, where: str) -> Any:
    if key not in raw:
        raise MissionValidationError(f"{where}: missing required key '{key}'")
    return raw[key]


def _as_float(value: Any, where: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise MissionValidationError(
            f"{where}: expected a number, got {type(value).__name__} ({value!r})"
        )
    result = float(value)
    if math.isnan(result) or math.isinf(result):
        raise MissionValidationError(f"{where}: must be finite, got {value!r}")
    return result


def _positive(value: Any, where: str) -> float:
    result = _as_float(value, where)
    if result <= 0.0:
        raise MissionValidationError(f"{where}: must be > 0, got {result}")
    return result


def _non_negative(value: Any, where: str) -> float:
    result = _as_float(value, where)
    if result < 0.0:
        raise MissionValidationError(f"{where}: must be >= 0, got {result}")
    return result


def _opt_positive(value: Any, where: str) -> Optional[float]:
    if value is None:
        return None
    return _positive(value, where)


def _latitude(value: Any, where: str) -> float:
    result = _as_float(value, where)
    if not -90.0 <= result <= 90.0:
        raise MissionValidationError(
            f"{where}: latitude must be in [-90, 90], got {result}"
        )
    return result


def _longitude(value: Any, where: str) -> float:
    result = _as_float(value, where)
    if not -180.0 <= result <= 180.0:
        raise MissionValidationError(
            f"{where}: longitude must be in [-180, 180], got {result}"
        )
    return result


# --- YAML entry points -------------------------------------------------------
def load_mission_yaml(text: str) -> Mission:
    """Parse a mission from a YAML string.

    Raises:
        MissionValidationError: On malformed YAML or an invalid mission.
    """
    if yaml is None:  # pragma: no cover
        raise MissionError("PyYAML is not installed; cannot parse mission YAML")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise MissionValidationError(f"mission YAML is not parseable: {exc}") from None
    return Mission.from_dict(data)


def load_mission_file(path: str) -> Mission:
    """Parse a mission from a YAML file on disk."""
    with open(path, "r", encoding="utf-8") as handle:
        return load_mission_yaml(handle.read())


def polygon_contains_geodetic(
    polygon: Sequence[Tuple[float, float]], origin: LocalOrigin, lat: float, lon: float
) -> bool:
    """True if a geodetic point lies inside a geodetic polygon (projected locally)."""
    local = [origin.geodetic_to_enu(a, b, origin.altitude_m)[:2] for a, b in polygon]
    e, n, _ = origin.geodetic_to_enu(lat, lon, origin.altitude_m)
    return point_in_polygon(e, n, local)


def polygon_centroid_geodetic(
    polygon: Sequence[Tuple[float, float]], origin: LocalOrigin
) -> Tuple[float, float]:
    """Area centroid of a geodetic polygon, returned as ``(lat, lon)``."""
    local = [origin.geodetic_to_enu(a, b, origin.altitude_m)[:2] for a, b in polygon]
    cx, cy = polygon_centroid(local)
    lat, lon, _ = origin.enu_to_geodetic(cx, cy, origin.altitude_m)
    return (lat, lon)
